---
editor_options: 
  chunk_output_type: console
---

# Where to next? 
<!-- This is just a placeholder title, I'm sure you can think of something better -->

This section is an opinionated list of aspects of science and programming that you may be interested in exploring next. Rather than writing in detail about *how* to do these things, which has been covered elsewhere, we explain *why* we think you may be interested in these elements, and provide links to resources so you can investigate further.  

  * The first chapter provides a brief overview of major sources of open source data, ranging from locations to time-stamps to trait measurements, and suggests packages that you can use for directly downloading data.  
  *  The second chapter [says something about how to merge datasets now that you've downloaded a bunch of open data].  
  *  The third chapter describes two different methods of working with big data. The datasets used in the main section of the book were chosen to illustrate the concepts being discussed, and have thus been quite small. However, working with biodiversity data can sometimes entail managing datasets many orders of magnitude larger. 
  *  The fourth chapter [git git git].
