project:
  type: book
  output-dir: _book
  resources: 
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"

book:
  title: "Cleaning Biodiversity Data in R"
  subtitle: "Atlas of Living Australia's practical guide to cleaning ecological data in R"
  favicon: images/cleaner-shrimp_cover.png
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  repo-url: https://github.com/AtlasOfLivingAustralia/cleaning_data/
  sidebar:
    logo: images/ALA_Logo_Inline_RGB.png

  page-footer:
    border: true
    left: |
      Cleaning Biodiversity Data in R is a product of <a href="https://ala.org.au/">![](/images/ALA_Logo_Inline_RGB.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    center: |
      ![](/images/NCRIS_logo.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}![](/images/CSIRO_logo.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}![](/images/GBIF-2015.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>. This work is licensed under a [CC-BY-NC-ND 4.0 Int License](https://creativecommons.org/licenses/by-nc-nd/4.0/)

  cover-image: images/cleaner-shrimp_cover.png

  chapters:
  - index.qmd
  - preface.qmd
  - introduction.qmd
  - data-in-this-book.qmd
  - part: 1_exploring/1_intro.qmd
    chapters:
    - 1_exploring/inspect.qmd
    - 1_exploring/summarise.qmd
  - part: 2_cleaning_general/1_intro.qmd
    chapters:
    - 2_cleaning_general/column-names-and-classes.qmd
    - 2_cleaning_general/duplicates.qmd
    - 2_cleaning_general/missing-values.qmd
    - 2_cleaning_general/strings.qmd
    - 2_cleaning_general/dates.qmd
  - part: 3_cleaning_expert/1_intro.qmd
    chapters:
    - 3_cleaning_expert/taxonomic-validation.qmd
    - 3_cleaning_expert/geospatial-investigation.qmd
    - 3_cleaning_expert/geospatial-cleaning.qmd
  appendices:
  - 4_appendices/where-to-get-data.qmd
  - 4_appendices/big-data.qmd
  - 4_appendices/data-scope.qmd
  - 4_appendices/joins.qmd
  - 4_appendices/reproducible-workflows.qmd
  - 4_appendices/git.qmd
  - packages.qmd
  - references.qmd

bibliography: 
  - references.bib
  - data-cleaning-book-references.bib

format:
  html:
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme: 
      - theme.css
      - theme.scss
      - lumen

execute:
  code-annotations: hover
  number-depth: 3

