project:
  type: book
  output-dir: _book

book:
  title: "ALA's Data Cleaning Booklet"
  subtitle: "A practical guide to cleaning ecological data"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
#  author: "Atlas of Living Australia"
#  date: "18/11/2022"

  page-footer:
    left: |
      The Data Cleaning booklet is a product of the <a href="https://ala.org.au/">Atlas of Living Australia</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: images/book_cover2.jpg 

  # Have the option to add introductory pages for the parts 
  # as in, part: part_intro.qmd
  chapters:
  - index.qmd
  - intro.qmd
  - data.qmd
  - part: 1_accessing/access_intro.qmd
    chapters:
    - 1_accessing/where-to-get-data.qmd
    - 1_accessing/large-downloads.qmd
    - 1_accessing/merging.qmd
  - part: 2_exploring/1_intro.qmd
    chapters:
    - 2_exploring/inspect.qmd
    - 2_exploring/summarise.qmd
  - part: 3_cleaning_general/1_intro.qmd
    chapters:
    - 3_cleaning_general/duplicates.qmd
    - 3_cleaning_general/missing-values.qmd
    - 3_cleaning_general/unexpected-values.qmd
    - 3_cleaning_general/strings.qmd
    - 3_cleaning_general/dates.qmd
    - 3_cleaning_general/column-names-and-classes.qmd
  - part: 4_cleaning_expert/1_intro.qmd
    chapters:
    - 4_cleaning_expert/taxonomic-synonyms.qmd
    - 4_cleaning_expert/taxonomy.qmd
    - 4_cleaning_expert/geospatial.qmd
    - 4_cleaning_expert/outliers.qmd
  - references.qmd
  - packages.qmd
  - appendix.qmd
  - part: cleaning_intro.qmd
    chapters:
    - cleaning_standardisation.qmd
    - cleaning_duplicates.qmd
    - cleaning_manipulating_strings.qmd
    - cleaning_taxonomy.qmd
    - cleaning_taxonomic_validation.qmd
    - cleaning_geospatial.qmd
    - outliers.qmd

bibliography: references.bib

format:
  html:
    mainfont: Roboto
    monofont: Fira Code
    monobackgroundcolor: "#F7F7F7"
    theme: 
      - lumen
      - theme.css
  pdf:
    documentclass: scrreprt

editor: source

