project:
  type: book

book:
  title: "ALA Data Cleaning"
  reader-mode: true
#  author: "Atlas of Living Australia"
#  date: "18/11/2022"
  page-footer:
    left: |
      Data Cleaning booklet is a product of the Atlas of Living Australia.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: images/book_cover2.jpg 

  chapters:
    - index.qmd
    - intro.qmd
    - scope.qmd
    - download-data.qmd
    - preclean.qmd
    - taxonomy.qmd
    - spatial.qmd
    - duplicates.qmd
    - outliers.qmd
    - summary.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

