project:
  type: book
  output-dir: _book

book:
  title: "ALA's Data Cleaning Booklet"
  subtitle: "Atlas of Living Australia's practical guide to cleaning ecological data"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    search: true 
    logo: images/ala.jpg
#  author: "Atlas of Living Australia"
#  date: "18/11/2022"

  page-footer:
    left: |
      The Data Cleaning booklet is a product of the <a href="https://ala.org.au/">Atlas of Living Australia</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: images/book_cover2.jpg 

  chapters:
  - index.qmd
  - intro.qmd
  - data-in-this-book.qmd
  - part: 1_exploring/1_intro.qmd
    chapters:
    - 1_exploring/inspect.qmd
    - 1_exploring/summarise.qmd
  - part: 2_cleaning_general/1_intro.qmd
    chapters:
    - 2_cleaning_general/column-names-and-classes.qmd
    - 2_cleaning_general/duplicates.qmd
    - 2_cleaning_general/missing-values.qmd
    - 2_cleaning_general/strings.qmd
    - 2_cleaning_general/dates.qmd
  - part: 3_cleaning_expert/1_intro.qmd
    chapters:
    - 3_cleaning_expert/taxonomic-validation.qmd
    - 3_cleaning_expert/geospatial-investigation.qmd
    - 3_cleaning_expert/geospatial-cleaning.qmd
  - 4_accessing/where-to-get-data.qmd
  - 4_accessing/big-data.qmd
  - 4_accessing/joins.qmd
  - 4_accessing/git.qmd
  - references.qmd
  - packages.qmd
  - appendix.qmd

bibliography: references.bib

format:
  html:
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme: 
      - lumen
      - theme.css
      - theme.scss

execute:
  code-annotations: hover
  number-depth: 3

