project:
  type: book

book:
  title: "ALA Data Cleaning"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
#  author: "Atlas of Living Australia"
#  date: "18/11/2022"
  output-dir: docs
  code-annotations: below
  navbar:
    background: none
    search: true
    left:
      - text: "Home"
        file: index.qmd
    pinned: false
  sidebar:
    title: "ALA Data Cleaning"
    style: docked
    background: none

  page-footer:
    left: |
      The Data Cleaning booklet is a product of the Atlas of Living Australia.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: images/book_cover2.jpg 

  # Have the option to add introductory pages for the parts 
  # as in, part: preface.qmd
  chapters:
  - part: index.qmd
    chapters:
    - overview.qmd
    - how_to_use.qmd
    - requirements.md
  - intro.qmd
  - part: scope.qmd
    chapters:
    - scope_temporal.qmd
    - scope_taxonomic.qmd
    - scope_spatial.qmd
    - scope_summary.qmd
  - part: "Open source biodiversity data"
    chapters:
    - download-data.qmd
    - preclean.qmd
  - part: "Data cleaning"
    chapters:
    - taxonomy.qmd
    - taxonomy-2.qmd
    - spatial.qmd
    - outliers.qmd
    - references.qmd
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, theme.css]
  pdf:
    documentclass: scrreprt

editor: source

