---
code-annotations: below
df-print: kable
---

# How to use this book {.unnumbered}

This book provides an overview of biodiversity data cleaning using the R
programming language. Demonstrations and instructions are accompanied by
code blocks, which show how a particular task was executed. Code blocks may also
include comments which are preceded by a `#` symbol, and are not executed by R:

```r
# This is a code block with a comment
library(package)
plot(data)
```

When performing a sequence of related actions, we use the native R pipe operator
`|>`. This allows multiple operations to be performed, without needing to save
the intermediate results to a variable. You can learn more about the pipe in the
[R for Data Science](https://r4ds.hadley.nz/data-transform.html#sec-the-pipe)
book. Some code blocks may also be **annotated**, to help explain the sequence
of steps. See the below example which uses the native R pipe, and is annotated:

```{r}
# This is a code block with annotation
mtcars |> # <1>
   dplyr::group_by(cyl) |> # <2>
   dplyr::summarise(mpg = mean(mpg)) # <3>
```
1. Using the pipe operator to pass the `mtcars` data frame to the `group_by()` function
2. Grouping the data frame by the `cyl` variable
3. Print a summary of the filtered data frame using the `summarise()` function

