# Metadata

Metadata describes your data set: it defines each variable and its contents.
This might be describing what units a variable has been measured in, or, the
climate the occurrence was collected in and whether it is a marked outlier.
**Starting the process of pre-cleaning by briefing your metadata allows you to
understand the kind of data you are working with and any potential biases that
may limit what you can do with it**. Similarly, these biases may need to be of
consideration when creating models or when used in your work more broadly. 

Data infrastructures that use Darwin Core terms will have interoperable
metadata. This makes it easier to consolidate across data sets. All Darwin Core
term definitions can be found [here](https://dwc.tdwg.org/terms/), we suggest
using `Ctrl/CMD F` and searching your variable name on the
[webpage](https://dwc.tdwg.org/terms/). Don't hesitate to Google variable names
if you are unsure what they represent.

It is also worth checking the metadata for the entire dataset to delineate if
there is extra information about the data which may be relevant. You could
Google the dataset name, or search the dataset or institution on the ALA. The
metadata on the ALA is submitted with the data, of which the ALA as a repository
and not an owner cannot change. This means low-quality metadata cannot
necessarily be vetoed. 

An example of well formatted metadata is [FrogID from the Australian
Museum](https://collections.ala.org.au/public/show/dr14760). From reading
FrogID's metadata [@rowley2020frogid], you'll find:

1. The data is acoustic data, the majority of the species recorded are
therefore male 
2. Because this is citizen science data, it is especially biased
towards populated areas 
3. Audio is recorded via a smartphone app, and so the authors
recommend to filter data to `geographic uncertainty of <3000m` if you require
high coordinate precision
4. The data is presence only data

Metadata can also be useful for understanding the license that the data falls
under. This is mostly relevant for using or republishing multimedia associated
with the data.