#note this section will come after download-data (to be re-arranged)

# Standardise Taxonomy  {#sec-standardise-taxonomy}

New species are being discovered and described all the time. Keeping up-to-date with the taxonomic literature can be challenging, where many taxonomic changes result from the rapid rise of new analytical tools, especially in the molecular field. Species historically described solely based on morphological characters are now being revealed as multiple species based on genomics, population genetic studies, and integrative approaches, where many lines of evidence are used to delimit and describe new species.

Due to the dynamism of taxonomy it can sometimes be difficult to have consistent data from multiple databases. The scientific community will not always agree on the classification of species and therefore these classifications can vary, resulting in multiple phylogeny trees for the same species or different subspecies etc.

If you've downloaded data from an online biodiversity database a naming authority will have been used to classify species. You may have gotten data from multiple sources where species are categorized differently.

So how do you deal with taxonomic inconsistencies?

## Naming authorities

Using a naming authority is a good way to help decide which taxonomic categorization of the data you're working with is correct. Accurate species delimitation is essential for understanding evolutionary processes and for adequate conservation management, as species-level lists are the foundation of conservation decisions, as is the IUCN Red List (@melville21). Yet, there are many databases for determining species taxonomy, and deciding which one to follow can take time and effort.

### Taxonomic shortfalls

Recent studies have described many taxonomic shortfalls (ref), such as differences in species concepts, subspecies and other sub-specific categories, and groups who's taxonomy is constantly changing.

There are many databases that contain information on species lists, barcode for example, is a database of genetic sequences for determining species.

**Problems to be considered when checking taxonomy: - issue of incorrect taxonomy identification - synonymies** (this section needs to be expanded out)

### Choosing a naming authority

It is essential to know what you are studying, is it an individual species or a group of species, this could influence what naming authority you choose to use for decision making.

A knowledge of taxonomy is essential in order to verify the data you are working with. For this, different organizations provide updated lists of species or even details of the taxonomic history of a species. Checking changes in taxonomy can be helpful when interpreting old data which may have species names you don't recognize. Changes in taxonomy, such as species split, new higher level classification (as genera), or species descriptions, highlight the importance of keeping up-to-date with taxonomic literature. This can be achieved by consulting the literature. Most taxonomic society groups release annual updates on taxonomy. The [Atlas of Living Australia (ALA)](www.ala.org.au) can also be used to investigate taxonomic changes.

In Australia, the [Australian Plant Name Index (APNI)](https://www.anbg.gov.au/apni/) is the primary naming authority for plants. With the [Australian Faunal Directory (AFD)](https://biodiversity.org.au/afd/home) the main taxonomic catalog for animal species. These authorities provide a list of accepted and authoritative names as a template. If you're unsure what naming authority to use, APNI and the AFD are a good place to start, especially if the data you're investigating covers a wide range of taxa. If you're investigating certain taxa it's worth checking when the taxonomy was last updated in the APNI or AFD, especially if you know there has been recent changes. If you want to investigate closer, we've provided some links to society groups, in some cases these can be more up to date that the APNI or AFD.

### Australian taxonomic society groups

**VERTEBRATES**

-   Amphibians and reptiles - [Australian Herpetological Society](https://ahs.org.au/)\
-   Birds - [Birdlife Australia](https://www.birdlife.org.au/)\
-   Fish - [Australian Society for Fish Biology](https://www.asfb.org.au/)\
-   Mammals - [The Australian Mammal Society](https://australianmammals.org.au/)

**INVERTEBRATES**

-   Arachnology - [Australasian Arachnological Society](www.australasianarachnologicalsociety.org)\
-   Entomology - [Australian Entomological Society](https://www.austentsoc.org.au/)\
-   Malacology - [The Malacological Society of Australasia](https://www.malsocaus.org/)\
-   Nematology - [Australasian Association of Nematologists](https://www.nematologists.org.au/)

## What to do with the naming authority 

Now that you've chosen a naming authority you'll want to use it to ensure the data you're working with has consistent taxonomy

```{r}

```
