# Open source data

"The Atlas of Living Australia is a data aggregator, we collate data from our
providers making them available to our users. The ALA does not own the data we
display. The data we receive come in different forms and of different qualities,
bringing many challenges. Data errors can occur in multiple places from data
collection through the ingestion process. Understanding that not all errors are
the same can help users work with the data they receive from us. "

"Conversely, others conclude that in a large majority of cases, high quantity,
low quality data produce similar results to that of lower quantity, high quality
data (Aceves-Bueno et al., 2017). Poor quality data have also been used to
cost-effectively estimate risk levels for data deficient species using a double
sampling methodology (see Bland et al., 2015). However, to date, the general
consensus within the conservation community favors the use of high quality data
(Cayuela et al., 2009; Wood, Sullivan, Lliff, Fink, & Kelling, 2011) "

With broad data accumulation data quality can be impacted. In response GBIF
flags potential errors through its data validator
(https://www.gbif.org/tools/data-validator). This is an automated process
providing information on geographic discrepancies (e.g., whether coordinates
fall within a stated country), meta-data structure and formatting issues, and
suggests how the user may improve the quality of the data and associated
meta-data before use. 