# Outliers
<!-- Notes -->
<!-- support article around inconsistent sampling and open source data -->

An outlier is a point located at a significant distance from the majority of the
species' distribution or available data points. Outliers can be true outliers or
data errors. Data errors can be caused by a variety of factors including
mis-identified specimens or incorrect georeferencing. In the absence of a data
error however, these outliers are considered to be a true point, and are not
necessary to remove.




- Alpha hull (some example species - check cailtin chat history)
alpha hull
examples for how to detect outliers, or how they can skew your data. 

-   Remove records with miss-identified taxonomy: Incorrectly identified species, or unrecognized species names compared to a naming authority, should be removed.

Incorrectly identified specimens can be difficult to identify with open source biodiversity data. Often these will be picked up by 1: an image of the species in question which does not match 2: If you notice a species outside of its geographic range, this could be a true outlier, it could be a spatial error, or it could be a different species. (**see --- for more info**)

## Alternative methods

Here we document some other existing methods that can be used for outlier
detection, and their limitations.

-  Species Distribution Modelling for outlier detection: 
    - [@simoes2018utility](https://doi.org/10.1111/icad.12288)
    - Maxiomum Entropy modelling (MaxEnt) was used to model habitat suitability
    for five species of leaf beetles in the genus *Mesomphalia*
    - The method relies on the assumption that an errornous point will have a
    lower habitat suitability value than a true point. 
    - For their dataset, the method was useful for identifying geographical
    position errors, but not species level identification errors.

<!-- I think this study / method also has some limitations - it relies on the
assumption that you are able to sensibly model the habitat suitability of your
species, with available environmental data and occurrence records. It would be
unsuitable for somebody with limited experience in SDMs. What environmental data
to use for predictors, what time scale - does it match your points, what spatial
scale and importance of scale, this isn't discussed. Their models have
suspiciously high AUC values, seems overfit. The claim that the method should be
more efficient in larger datasets is unsubstantiated. How do you verify the
results? All you know is that the habitat suitability is lower than expected
relative to your other samples. It could be due to sampling bias, and
underrepresented environmental areas. How exactly would you determine the
cut-off for identifying outliers? Not discussed.  -->
