# Overview and structure {.unnumbered}

This book acts as a general guide on downloading and cleaning biodiversity data
using R. If you are new to working with biodiversity data in R, or hoping to add
some tips and code examples to your toolbox, then this book is for you. However,
this is not a guide to R itself, and so a basic familiarity with the language is
recommended. 

We will cover the most common steps associated with cleaning open-access
georeferenced biodiversity data, broken down into three sections. An overview of
the three sections and what they cover:

-  **Data scope** 
  - What is data scope?
  - How to determine the termporal, taxonomic, and spatial scope of available
  data for your study 
- **Accessing data** 
  - Where to get data from?
  - How to download data using R
  - How to refine download queries
  - First steps in data inspection
- **Data cleaning** 
  - String manipulation
  - Taxonomic standardisation (synonyms, naming authorities, duplicates)
  - Spatial data cleaning
  - Outlier detection

The areas of research and uses of biodiversity data are many and varied. Here we
have focused on just one facet - downloading and cleaning georeferenced
occurrence / biodiversity data. As such, this book will not cover:

- Hypothesis testing or experimental design
- How to clean environmental data that is not occurrence / biodiversity data (e.g. trait data) 
- How to perform analyses (e.g. species distribution modelling) 

::: {.callout-warning appearance="simple"} 

**There is no one size fits all workflow**.

Data cleaning steps are frequently completed in entirely different orders, and
this is just one example of a data cleaning workflow. Although it is possible to
follow this book sequentially, this book does not have to be used in a linear
fashion. *While some steps may logically come first, they may need to be
revisited after completing another.*

:::
