---
editor: 
  markdown: 
    wrap: 72
code-annotations: hover
number-depth: 3
---

## Data scope

Data scope refers to the type and extent of data needed for your project.
Defining your scope is an essential part of forming a research question,
ultimately impacting what data you will use in your project. Availability of
data may therefore influence your scope and research question.

For example, you might have a question about several species in the same area.
However, data for one or more of those species could be limited because
observations are rare, surveying the area where it lives is difficult, or only
several historical records exist. 

Without narrowing your data scope, you might find yourself downloading more data
than you need, which can needlessly increase how much time is spent processing
data prior to analyses. Alternatively, you might find there isn't enough data to
answer your question.

While there are workable methods to analyse small sets of biodiversity data
(e.g. [hulls](https://labs.ala.org.au/posts/2022-10-12_alpha-hulls/post.html)),
it's worth thinking critically about whether the amount of data available will
allow you to sufficiently answer your research question.

To start, some initial questions you might ask are:

-   What is the **temporal** unit relevant for your research question?

    *Am I only interested in more recent data? Is there data that are too old to
    be relevant for my question?*

-   What is the **taxonomic** unit of your proposed research question?

    *Is my question specific to one or more species in the same taxonomic group?
    Does it compare between higher taxonomic levels like genus, family or
    order?*

-   What is the **spatial** scale of your proposed research question?

    *Is my question relevant at a global or national level, or is it specific to
    a region or ecosystem?*

Questions like these will help you define what data is most relevant for your
research question, and help you begin to think about how much evidence
available, and the trade-offs you might make between the specificity of your
question and the certainty of your answer.