---
title: "Accessing biodiversity data"
format: html
---

The aim of this section is to demonstrate the process of going from a planned data scope, to a complete, ready for cleaning dataset. We will demonstrate an example workflow for accessing biodiversity data, from downloading data, to integrating data from multiple sources. Along the way we will also highlight some of the important concepts and challenges to be aware of, such as taxonomic name variation across data aggregators, and working with disparate data sources.

Outline of chapters:

- Download data:
  - Introduce some common open access biodiversity data infrastructures
  - How to access this data, including download queries and filtering techniques
- Initial inspection:
  - How to assess a downloaded dataset as to whether it matches your expectations
- Dataset integration:
  - How to integrate data from multiple sources into a single dataset

::: {style="display: flex; flex-wrap: wrap; justify-content: space-between; margin-left: 20px; margin-right: 20px; margin-bottom: 20px; text-align: center"}

::: {style="width: 25%; justify-content: space-between"}
<div class="circle-button">
  [{{< fa magnifying-glass size=3x >}}](where-to-get-data.html)
</div>
[**Find data**]{style="color: #efa123; font-size: 15.5px; text-align: center"}
:::

::: {style="width: 25%; text-align: center; justify-content: space-between"}
<div class="circle-button">
  [{{< fa bars-progress size=3x >}}](large-downloads.html)
</div>
[**Large downloads**]{style="color: #efa123; text-align: center;"}
:::

::: {style="width: 25%; text-align: center; justify-content: space-between"}
<div class="circle-button">
  [{{< fa object-ungroup size=3x >}}](merging.html)
</div>
[**Merging data**]{style="color: #efa123; text-align: center"}
:::

:::