---
editor_options: 
  chunk_output_type: console
---

<!-- Note from Dax here! I think putting too much detail here will be very offputting, but knowing about naming authorities and being aware that it's something you need to check is important to speak about at this point in the book. I think it might be best to vaguely explain what a naming authority is, and that there are many of them because taxonomy is hard. Then extra information can be placed in an appendix at the end of the chapter? Or at the end of the book? At the moment, I've pasted what I think is excess information at the bottom of the chapter. --> 

<!-- Main point: It's worth being aware of what naming authority your taxonomic backbone uses. In some taxonomic groups, these can vary widely. Double checking your data after your download to make sure the classifications you expect are what you have will help prevent errors later on. Otherwise, you can re-code data with incorrect classification manually. --> 

<!-- Notes/Andrew: Strong agree with above, I think any advice specific to
taxonomy, choosing an authority etc should be avoided and I've added this
content to reflect that. -->

# Taxnomy and open source data

Taxonomy is a complex and broad field of investigation, and a comprehensive
discussion of this area is beyond the scope of this book. However, we will
highlight some key principles that should be considered before moving on and
downloading data, as they can directly impact the data collection and cleaning
process. 

::: {.callout-important}
We strongly advise that before downloading data, a thorough investigation of the
taxonomic classification of your study organism(s) be conducted, as well as
identifying potential naming differences across data sources. This will help to
avoid confusion and errors later on, during the data cleaning process.
:::

## Taxonomic authorities

Taxonomic classifications and groupings can vary over time, and between data
data sources and aggregators. To ensure consistency in the classifications of
biodiversity data, data aggregators use something called a 'taxonomic backbone',
which is essentially a reference framework that dictates which taxonomic names
are used for organisms in their system. GBIF uses a [taxonomic
backbone](https://tinyurl.com/gbifdata) that is based on a wide variety of
authority sources. Other data aggregators (such as the ALA), use their own
taxonomic backbone of authority sources for classification. As a result,
**taxonomic classifications can vary across data aggregators and sources.**

These sources that make up taxonomic backbones are typically authoritative
databases or naming authorities. These authorities are usually an organisation
or institution that has the responsibility and expertise to formally name and
classify living organisms, and this process is governed by various international
codes of nomenclature. As an example, the ALA uses the [Australian Plant Name
Index (APNI)](https://www.anbg.gov.au/apni/) as the primary naming authority for
plants, and the [Australian Faunal Directory
(AFD)](https://biodiversity.org.au/afd/home) as the main taxonomic catalog for
animal species (for a full list, see the
[appendix](#appendixNamingAuthorities)). 

With this in mind, it is important to first familiarise yourself with the
taxonomic classification of your study organism(s), and any variations across
different sources and naming authorities. Following this, you should ensure that
you adhere to a single taxonomic classification system for your organism. Later
in this book, we demonstrate techniques for cleaning and standardising taxonomic
names, which is particularly important when working with an organism that has
classification differences across sources. 

::: {.callout-caution}
Data that doesn't match your preferred naming authority or contains data from
multiple naming authorities may need to be conformed to a single taxonomic
backbone. See the [placeholder]() section (or appendix) for more information on
how to do this.
:::

<!-- Dax comments: -->
<!-- Might be worth showing how in an appendix -->.
<!-- In appendix, it's worth showing a few things: -->
<!--     how to query with your ideal species list, some systems fuzzy match and will have synonyms -->
<!--     getting all the name columns including your own preferred naming authority to check if you back correct -->

# Appendix: Naming Authorities {#appendixNamingAuthorities}
<!-- Andrew: Migrated this from downloads. Haven't reflowed it for this section -->
Accurate species delimitation is also crucial for adequate conservation
management and understanding evolutionary processes ([Mace
2004](http://localhost:3271/references.html#ref-mace2004role)). Species level
lists are the foundation of many conservation decisions: such as the IUCN
conservation status classification system. Taxonomic scope therefore has an
effect on research application impacts.

Deciding what naming authority to use can be challenging. What you choose will
depend on your own taxonomic research and evaluation, but also your research
scope.

<!-- Dec/2020 - RE: Image / table for ALA naming authorities -->
<!-- Dax note: I think that this information should be put in a simpler table and maybe just link out to all of the authority websites. It's just so much information in one graphic, so I think adding links would be a easy compromise? -->
<!-- Notes/Andrew: Agree, I don't like the image and its not even really relevant. Removing it. -->

These authorities provide a list of accepted and authoritative names as a
template. If you're unsure what naming authority to use and you're looking at
Australian species, the APNI and the AFD are a good place to start, especially
if the data you're investigating covers a wide range of taxa. If you're
investigating specific taxa it's worth checking when the taxonomy was last
updated in the APNI or AFD, especially if you know there has been recent
changes. If you want to investigate closer, we've provided some links to society
groups, in some cases these can be more up to date that the APNI or AFD.